### ISSUE TITLE
Add parameter n_segments to cv2_extras.utils.generate_background_contours

### ISSUE THREAD

**Issue by benneely** [whitews/cv2-extras#2]
There is already a TODO in the code base related to this issue. This is a request to go ahead and provide a parameter in the function signature that allows users to specify the number of segments (as opposed to always generating 200).

**Comment by whitews** [comment]
@benneely I've added the option with 200 as the default. Note, there's also some hard-coded min and max contour sizes in that function as well. Not sure if they will cause you problems but we should think about exposing those too.
